config/routes.rb
Rails.application.routes.draw do
    
  get 'tweets/show'
  devise_for :tweets
    root 'tops#index'
    
    get 'searches/new'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    get 'tops/index2'
    
    #get 'users/main'
    #post 'users/login'
    #get 'users/logout'
    get 'signup' => 'users#new'
    post 'signup' => 'users#create'
    get 'users/:id' => 'users#show'
    resources :users, only: [:create]
    
    get 'posts/new' => 'posts#new'
    get 'posts/index3' => 'posts#index3'
    get 'posts/:id' => 'posts#show'
    patch 'posts/:id' => 'posts#update'
    get 'posts/:id/edit' => 'posts#edit', as:'edit_post'
    post 'posts' => 'posts#create'
    resources :posts do
      resources :likes, only: [:create, :destroy]
    end
    
    resource :sessions, only: [:new, :create, :destroy]
    get '/login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    
    get 'corporate_signup' => 'corporates#new'
    post 'corporate_signup' => 'corporates#create'
    resources :corporates, only: [:create]
    
    get 'corporate_login' => 'corporate_users#new'
    post 'corporate_login' => 'corporate_users#create'
    delete 'corporate_logout' => 'corporate_users#destroy'
    get 'corporate_user_show' => 'corporate_users#show'

    resources :tweets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/corporate.rb
class Corporate < ApplicationRecord
    has_secure_password validations: true
    
    before_save {self.name=name.downcase}
    validates :name,presence: true
    validates :password,presence: true
    
    def self.new_remember_token
        SecureRandom.urlsafe_base64
    end
    def self.encrypt(token)
        Digest::SHA256.hexdigest(token.to_s)
    end
end

app/models/corporate_user.rb
class CorporateUser < ApplicationRecord
    has_secure_password
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
  validates_uniqueness_of :post_id, :user_id
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user, optional: true

    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    
    validates :start_on,presence: true
    validates :end_on,presence: true
    
    enum status: {open: 0,closed: 1}
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/session.rb
class Session < ApplicationRecord
    has_secure_password
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :text, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

    has_many :tweets
    has_secure_password
    has_many :posts, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :liked_posts, through: :likes, source: :posts
    
    before_save {self.email=email.downcase}
    validates :age,presence: true
    validates :gender,presence: true
    validates :email, presence: true
    validates :password,presence: true
    validates :password_confirmation,presence: true
    
    def self.new_remember_token
        SecureRandom.urlsafe_base64
    end
    def self.encrypt(token)
        Digest::SHA256.hexdigest(token.to_s)
    end
    def already_liked?(post)
        self.likes.exists?(post_id: post.id)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
 def create
 end

 def destroy
 end
 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    require 'date'
    def new
        @post=Post.new
    end
    def index3
        @posts=Post.all.order(end_on: :asc)
        @corporate=Corporate.find_by(params[:name])
        special_post_ids=Post.where.not(start_on: nil).pluck(:id)
        @special_posts=Post.where(id: special_post_ids).where('start_on <= ?', Date.today).where('end_on >= ?', Date.today)
    end
    def create
        @posts=Post.all
        post = Post.new(post_params)
        if post.save!
            redirect_to :action => "index3"
        else
            redirect_to :action => "new"
        end
        
        #@date=Date.today
        #@start_on=Date.to_param[:start_on]
        
        #sabun=(@start_on - @date)
        #unless sabun>=1
        #    flash[:error]="開始日は明日以降で！"
        #    render 'new'
        #    return
        #end
        
        #sabun=(@posts.end_on-@posts.start_on).to_i
        #unless sabun<=10
        #    flash[:error]="期日は最長10日間まで！"
        #    render 'new'
        #    return
        #end
        
        #unless sabun>=0
        #    flash[:error]="終了日は開始日以降で！"
        #    render 'new'
        #    return
        #end
        
    end
    
    def edit
        @post=Post.find(params[:id])
    end
    
    def update
        post=Post.find(params[:id])
        if post.update(post_params)
            redirect_to :action =>"index3"
        else
            redirect_to :action =>"new"
        end
    end

    private
    def post_params
        params.require(:post).permit(:title, :body, :start_on, :end_on)
    end
    def corporate_params
      params.require(:corporate).permit(:name)
    end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
    def index
    end
    def index2
        @user=User.find_by(user_params[:age])
    end
    private
    def user_params
        params.permit(:age, :gender, :email, :password, :password_confirmation)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show]
  def show
    @current_user=corporates_url.id
  end
  
  private
  def set_tweet
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def main
        if user_signed_in?
            render 'index2'
        else
            render 'sign_up'
        end
    end
    
    def login
        if params[:age] == "kindai" and params[:gender] == "sanriko"
            session[:login_uid] = params[:gender]
            redirect_to tops_index2_path
        else
            render 'login_failed'
        end
    end
    
    def logout
        session.delete(:login_uid)
        redirect_to roo_path
    end
    def new
        @user=User.new
    end
    def create
        @user=User.new(user_params)
        if @user.save!
            redirect_to login_path
        else
            render 'tops/index'
        end
    end
    def show
        @nickname=current_user.nickname
        @tweets=current_user.tweets
    end
    private
    def user_params
        params.require(:user).permit(:age, :gender, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/corporates_helper.rb
module CorporatesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id]=user.id
    end
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    def logged_in?
        !current_user.nil?
    end
    def log_out
        session.delete(:user_id)
        @current_user=nil
    end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/likes/like.html.erb
<div class="option" >
    <div class="favorite-btn">
        <p><span>お気に入り登録: </span><%=link_to @post.likes.count, likes_path(@post.id), method: :post %></p>
    </div>
    <div class="report-btn">
        <p><span>お気に入り解除: </span><%=link_to @post.likes.count, like_path(@post.id), method: :delete %></p>
    </div>
    <div class="count-btn">
        <p><span>お気に入りされた数: </span><%= @post.likes.count %></p>
    </div>
</div>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
    <%= f.label :title, '商品名' %>
    <%= f.text_area :title, :size => 140 %><br>
    <%= f.label :body, '価格' %>
    <%= f.text_area :body, :size => 140 %>
    <%= f.submit '編集する' %>
<% end %>

app/views/posts/index3.html.erb
<h1>投稿一覧</h1>
<% @posts.each do |f| %>
  <% if f.end_on < Date.today %>
  <% else %>
    <div class="box2">
      <div class="box2-title">
         <p><%= @corporate.name %></p>
        <%= f.title %>
        <div class="box2-body">
          <p>店頭税抜価格より：</p>
          <%= link_to f.body, edit_post_path(f.id) %>円引き
        </div>
      </div>
      <div class="box2-date">
        開始　<%= f.start_on %><%= "　　" %>終了　<%= f.end_on %>
      </div>
      <p><%= render partial: 'special_posts', collection: @special_posts, as: :post %></p>
    </div>
  <% end %>
<% end %>
<br>

<%= link_to 'show', '../users/show' %>
<!-- <%= link_to 'corporate_login', corporate_login_path %> -->
<%= link_to "back", root_path %>
<%= link_to "logout", corporate_logout_path, method: :delete %>

app/views/posts/new.html.erb
<span>
    <%= link_to "投稿一覧", "index3" %>
</span>

<h3>新規Post</h3>
<%= form_for @post do |f| %>
  <div class="field">
    <%= f.label :title, '商品名' %>
    <%= f.text_area :title, :size => 140 %><br>
    <%= f.label :body, '価格' %>
    <%= f.text_area :body, :size => 140 %><br>
    <%= date_field_tag 'post[start_on]' %>
    <%= date_field_tag 'post[end_on]' %>
  </div>
  <%= f.submit "Tweetする" %>
<% end %>
<%= link_to "一覧に戻る", "/" %>

app/views/posts/show.html.erb
<h2>タイトル</h2>
<p><%= @post.title %></p>
<h2>本文</h2>
<p><%= @post.body %></p>
<%= link_to "back", "index3" %>

<%= link_to "like", like_path %>

app/views/tweets/show.html.erb
<h1><%= @current_user.id %></h1>

app/views/users/login.html.erb
<%= form_tag "login", method: :post do %>
    <%= label_tag :age, 'age' %>
    <%= text_field_tag :age %>
    <%= label_tag :gender, 'gender' %>
    <%= password_field_tag :gender %>
    <%= submit_tag '登録' %>
<% end %>

app/views/users/login_failed.html.erb
ログインに失敗しました
<%= link_to "戻る", :back %>

app/views/users/main.html.erb
ログイン中です
<%= link_to 'ログアウト', users_logout_path %>

app/views/users/new.html.erb
<h1>ユーザー登録</h1>
<%= form_for(@user, url: signup_path) do |f| %>
  <%= f.label :age, 'age' %>
  <%= f.text_field :age %><br>
  <%= f.label :gender, 'gender' %>
  <%= f.text_field :gender %><br>
  <%= f.label :email, 'email' %>
  <%= f.password_field :email %><br>
  <%= f.label :password, 'パスワード' %>
  <%= f.password_field :password %><br>
  <%= f.label :password_confirmation, 'パスワード(確認)' %>
  <%= f.password_field :password_confirmation %><br>
  <%= f.submit '作成' %>
<% end %>
<%= link_to "back", "login" %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h5 class="modal-title" id="exampleModalLabel">設定</h5>
<%= link_to "back", "../posts/index3" %>